name: card_manager
description: "A new Flutter project for Card Manager."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: 4.6.6
  shared_preferences: 2.3.4
  sqflite: ^2.0.0+4
  path: ^1.8.0
  path_provider: ^2.0.7
  provider: ^6.1.2
  permission_handler: ^10.0.0
  geolocator: ^9.0.2
  flutter_svg: ^2.0.16
  intl: ^0.18.0
  confetti: ^0.8.0
  package_info_plus: ^8.1.3
  local_auth: ^2.3.0
  change_app_package_name: ^1.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

